In [1]:
import re
import numpy as np
import pandas as pd

In [2]:
corpus = [
    "I love NLP",
    "I love machine learning",
    "NLP is fun"
]

for i, document in enumerate(corpus):
    print(f"Document {i}: {document}")

Document 0: I love NLP
Document 1: I love machine learning
Document 2: NLP is fun


#### Text Preprocessing Function

In [3]:
def preprocess_text(text):
    text = text.lower()
    tokens = re.findall(r"[a-z]+", text)
    return tokens

for document in corpus:
    print(preprocess_text(document))

['i', 'love', 'nlp']
['i', 'love', 'machine', 'learning']
['nlp', 'is', 'fun']


#### Create Manually Vocabulary

In [4]:
unique_words = set()

for document in corpus:
    tokens = preprocess_text(document)
    
    for word in tokens:
        unique_words.add(word)
        
vocabulary = sorted(unique_words)
print("Vocabulary: ", vocabulary)
print("Vocabulary size:", len(vocabulary))

Vocabulary:  ['fun', 'i', 'is', 'learning', 'love', 'machine', 'nlp']
Vocabulary size: 7


In [5]:
word_to_index = {}

for i, word in enumerate(vocabulary):
    word_to_index[word] = i
    
print("Word to index mapping:")
for word, index in word_to_index.items():
    print(f"{word}: {index}")

Word to index mapping:
fun: 0
i: 1
is: 2
learning: 3
love: 4
machine: 5
nlp: 6


#### Manual Bag of Words Matrix

In [ ]:
bow_matrix = np.zeros(
    (len(corpus), len(vocabulary)),
    dtype=int
)

for document_index, document in enumerate(corpus):
    tokens = preprocess_text(document)
    
    for word in tokens:
        if word in word_to_index:
            word_index = word_to_index[word]
            bow_matrix[document_index][word_index] += 1

print(bow_matrix)

[[0 1 0 0 1 0 1]
 [0 1 0 1 1 1 0]
 [1 0 1 0 0 0 1]]
