In [1]:
import torch

### PyTorch tensor

In [2]:
tensor_1 = torch.tensor([1, 2, 3, 4, 5])

print("Tensor 1:", tensor_1)
print("Shape:", tensor_1.shape)
print("Data type:", tensor_1.dtype)

Tensor 1: tensor([1, 2, 3, 4, 5])
Shape: torch.Size([5])
Data type: torch.int64


In [3]:
tensor_2 = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

print("Tensor 2:")
print(tensor_2)
print("Shape:", tensor_2.shape)

Tensor 2:
tensor([[1, 2, 3],
        [4, 5, 6]])
Shape: torch.Size([2, 3])


In [4]:
random_tensor = torch.rand(3, 4)

print("Random Tensor:")
print(random_tensor)
print("Shape:", random_tensor.shape)

Random Tensor:
tensor([[0.2077, 0.5749, 0.5446, 0.4897],
        [0.2390, 0.3542, 0.8298, 0.3929],
        [0.9723, 0.0667, 0.2914, 0.2592]])
Shape: torch.Size([3, 4])


In [5]:
zeros_tensor = torch.zeros(2, 3)
ones_tensor = torch.ones(2, 3)

print("Zeros Tensor:")
print(zeros_tensor)

print("Ones Tensor:")
print(ones_tensor)

Zeros Tensor:
tensor([[0., 0., 0.],
        [0., 0., 0.]])
Ones Tensor:
tensor([[1., 1., 1.],
        [1., 1., 1.]])


### Tensor reshape

In [6]:
x = torch.arange(1, 13)

print("Original Tensor:")
print(x)
print("Original Shape:", x.shape)

Original Tensor:
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
Original Shape: torch.Size([12])


In [7]:
x_reshaped = x.reshape(3, 4)

print("Reshaped Tensor:")
print(x_reshaped)
print("New Shape:", x_reshaped.shape)

Reshaped Tensor:
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
New Shape: torch.Size([3, 4])


In [8]:
x_reshaped_2 = x.view(2, 6)

print("Another Reshaped Tensor:")
print(x_reshaped_2)
print("Shape:", x_reshaped_2.shape)

Another Reshaped Tensor:
tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])
Shape: torch.Size([2, 6])


### Device transfer

In [9]:
device = "cuda" if torch.cuda.is_available() else "cpu"

print("Available Device:", device)

Available Device: cpu


In [10]:
x_device =  x_reshaped.to(device)

print("Tensor Device:", x_device.device)
print(x_device)

Tensor Device: cpu
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])


In [11]:
x_cpu = x_device.to("cpu")

print("Back to CPU:")
print(x_cpu)
print("Device:", x_cpu.device)

Back to CPU:
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
Device: cpu


### Basic math operation

In [12]:
a = torch.tensor([10, 20, 30])
b = torch.tensor([1, 2, 3])

print("Tensor a:", a)
print("Tensor b:", b)

Tensor a: tensor([10, 20, 30])
Tensor b: tensor([1, 2, 3])


In [13]:
addition = a + b
print("Addition:", addition)

Addition: tensor([11, 22, 33])


In [14]:
subtraction = a - b
print("Subtraction:", subtraction)

Subtraction: tensor([ 9, 18, 27])


In [15]:
multiplication = a * b
print("Multiplication:", multiplication)

Multiplication: tensor([10, 40, 90])


In [16]:
division = a / b
print("Division:", division)

Division: tensor([10., 10., 10.])


In [17]:
power = a ** 2
print("Power:", power)

Power: tensor([100, 400, 900])


### Matrix multiplication

In [18]:
matrix_1 = torch.tensor([
    [1, 2],
    [3, 4]
])

matrix_2 = torch.tensor([
    [5, 6],
    [7, 8]
])


In [19]:
matmul_result = torch.matmul(matrix_1, matrix_2)

print("Matrix 1:")
print(matrix_1)

print("Matrix 2:")
print(matrix_2)

print("Matrix Multiplication Result:")
print(matmul_result)

Matrix 1:
tensor([[1, 2],
        [3, 4]])
Matrix 2:
tensor([[5, 6],
        [7, 8]])
Matrix Multiplication Result:
tensor([[19, 22],
        [43, 50]])


### Mean, sum, max, min

In [20]:
values = torch.tensor([10.0, 20.0, 30.0, 40.0])

print("Values:", values)

print("Sum:", torch.sum(values))
print("Mean:", torch.mean(values))
print("Max:", torch.max(values))
print("Min:", torch.min(values))

Values: tensor([10., 20., 30., 40.])
Sum: tensor(100.)
Mean: tensor(25.)
Max: tensor(40.)
Min: tensor(10.)
